version: "3.8"

services:
  postgres:
    image: postgres:14
    container_name: s-eda-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
      POSTGRES_DB: s_eda_db

  app:
    build: ./
    container_name: s-eda-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://postgres:5432/s_eda_db